### ISSUE TITLE
Depth map based on THuman2.0

### ISSUE THREAD

**Issue by gap705** [aipixel/GPS-Gaussian#26]
Thank you for your great work. I would like to ask a question. When generating a depth map based on THuman2.0, I set the radius to 0.8m. At this time, the depth value at a closer position will be wrong, but the RGB map is correct. What is the reason for this situation? How should I handle this? Thanks.

**Comment by ShunyuanZheng** [comment]
Hi @gap705, I have the following suggestions according to your questions:
(1) I think you should synthesize training data with a random depth range covering your test scenario.
(2) The saved inverse depth map in our task is less than 2.0 (real depth > 0.5), so I multiply 2^15 [here](https://github.com/ShunyuanZheng/GPS-Gaussian/blob/main/prepare_data/render_data.py#L22) for depth map saving. So, please check the value of your generated data to see whether the overflow problem happens (real depth < 0.5).
(3) After checking the data as in (2), I think a smaller depth challenges the two-view stereo depth estimation. As an example, we find forward hand movement degrades the rendering performance when GPS-Gaussian is applied in half-body real-time communication systems.

**Comment by gap705** [comment]
Thanks for your reply and help.

**Comment by gap705** [comment]
Hello, I set the radius to 0.8m , and multiplied it by 2**12 when saving the depth map according to your suggestion, and the depth map is correct. But at this time, the results of the verification set will be unclear. Is it because the depth value precision is not enough? Thanks.

**Comment by ShunyuanZheng** [comment]
I think 2^14 is enough for your case. The blurred results may caused by many factors, I think you can save the point clouds un-projected by binocular depth estimation to check whether the two partial point clouds are consistent. If a significant mismatch is witnessed, the problem should come from depth estimation or the precision of GT depth data saving.

**Comment by gap705** [comment]
Thanks again for your help.
