### ISSUE TITLE
about batchsize

### ISSUE THREAD

**Issue by huizhizhao** [aipixel/GPS-Gaussian#27]
Hello, thank you for your outstanding work! My GPU memory is limited, and during training, I set the batch size to 1. Why is the result blurry compared to others with batch size=2 under the same configuration? 
When batch size=2, the first record‘s round of validation in stage 2 is clear, but when batch size=1 val, each record's round is blurry. Continuing to increase the number of rounds does not seem to improve. Is it necessary to require batch size>=2?

**Comment by ShunyuanZheng** [comment]
Hi, @huizhizhao, I think it is not necessary to set batch size>=2 in stage 2. 
You could verify the epe loss of depth estimation to identify whether the degenerated depth estimator or the Gaussian parameter regressor causes the blurred results. Also, I think you could try to reduce the number of convolution kernels in the Gaussian parameter regressor, especially in high-resolution layers to satisfy the limitation of GPU memory.

**Comment by huizhizhao** [comment]
thanks for your help
