### ISSUE TITLE
怎么在只有四个视角的情况下正常渲染。

### ISSUE THREAD

**Issue by junjxiao** [aipixel/GPS-Gaussian#28]
你好， 如果输入的图片只有四个视角（前后左右）怎么能让方法work。由于对数据的预处理，目前代码应该是无法处理只有四个视角的情况？

**Comment by ShunyuanZheng** [comment]
您好，前后左右4个视点对我们的方法来说过于稀疏，目前应该是无法处理的，因为立体校正会将人体区域全部裁掉。全身人体中，6个视点应该是我们方法所能cover的极限情况了，并且FOV也应相应调大，使得立体校正后人体仍然能完整地出现在图像中。
