### ISSUE TITLE
3DoF or 6DoF?

### ISSUE THREAD

**Issue by leviome** [aipixel/GPS-Gaussian#30]
thanks for the nice work!

In my understanding, GPS-Gaussian leverage two adjacent views to synthesize novel view, if we want a view that is far from all source views, will GPS-Gaussian still work?

**Comment by ShunyuanZheng** [comment]
Thank you for your interest!

Our method still works if the mentioned novel viewpoint refers to a closer or a more distant one. However, the performance will degrade when synthesizing pitching viewpoints. This drawback is mainly caused by self-occlusion, which means it remains high-quality rendering in unoccluded regions.

**Comment by leviome** [comment]
thanks, got it !

The occluded regions may be reduced by involving more (>2) referring viewpoints, will GPS-Gaussian support it ?

**Comment by leviome** [comment]
By the way, I find that GPS-Gaussian doesn't involve any human-related priors, so it looks feasible in non-human-object NVS. Why did you title GPS-Gaussian as Human NVS?

**Comment by ShunyuanZheng** [comment]
> thanks, got it !
> 
> The occluded regions may be reduced by involving more (>2) referring viewpoints, will GPS-Gaussian support it ?

Directly aggregating more source views is not trivial. You can try to replace the binocular depth estimator with an MVS module.

**Comment by ShunyuanZheng** [comment]
> By the way, I find that GPS-Gaussian doesn't involve any human-related priors, so it looks feasible in non-human-object NVS. Why did you title GPS-Gaussian as Human NVS?

Yes, GPS-Gaussian is not limited to Human NVS. However, the real-time efficiency is highlighted in our method. Validation on static objects cannot showcase the main highlight of GPS-Gaussian while NVS on moving objects are not general applications. So our method can be widely used in Human-centered scenarios such as in holographic communication systems.

**Comment by leviome** [comment]
Got it, thanks for your kind reply!
