### ISSUE TITLE
关于渲染实时性

### ISSUE THREAD

**Issue by yqxuxuxu** [aipixel/GPS-Gaussian#34]
作者您好，我使用以下代码对渲染实时性进行了测试，但是结果只有4.fps，远没有论文列出的25fps这么高，不知道是我的操作有问题还是因为卡不一样呢？
```
        fps = []
        for idx in tqdm(range(total_frames)):
            item = self.dataset.get_test_item(idx, source_id=view_select)
            data = self.fetch_data(item)

            data = get_novel_calib(data, self.cfg.dataset, ratio=ratio, intr_key='intr_ori', extr_key='extr_ori')
            start_time = time.time() 
            with torch.no_grad():
                data, _, _ = self.model(data, is_train=False) 
                data = pts2render(data, bg_color=self.cfg.dataset.bg_color)
            end_time = time.time()  
            synthesis_time = end_time - start_time
            fps.append(1/synthesis_time)
            render_novel = self.tensor2np(data['novel_view']['img_pred'])
            
            cv2.imwrite(test_path  + '/%s_novel.jpg' % (data['name']), render_novel)

        print(sum(fps)/ len(fps))
```

**Comment by ShunyuanZheng** [comment]
python版本的差不多在5fps左右，实时系统需要把网络部分全部转成TensorRT，跟FloRen中类似。

**Comment by yqxuxuxu** [comment]
> python版本的差不多在5fps左右，实时系统需要把网络部分全部转成TensorRT，跟FloRen中类似。

好的，非常感谢。

**Comment by Wang-Chbo** [comment]
> 作者您好，我使用以下代码对渲染实时性进行了测试，但是结果只有4.fps，远没有论文列出的25fps这么高，不知道是我的操作有问题还是因为卡不一样呢？
> 
> ```
>         fps = []
>         for idx in tqdm(range(total_frames)):
>             item = self.dataset.get_test_item(idx, source_id=view_select)
>             data = self.fetch_data(item)
> 
>             data = get_novel_calib(data, self.cfg.dataset, ratio=ratio, intr_key='intr_ori', extr_key='extr_ori')
>             start_time = time.time() 
>             with torch.no_grad():
>                 data, _, _ = self.model(data, is_train=False) 
>                 data = pts2render(data, bg_color=self.cfg.dataset.bg_color)
>             end_time = time.time()  
>             synthesis_time = end_time - start_time
>             fps.append(1/synthesis_time)
>             render_novel = self.tensor2np(data['novel_view']['img_pred'])
>             
>             cv2.imwrite(test_path  + '/%s_novel.jpg' % (data['name']), render_novel)
> 
>         print(sum(fps)/ len(fps))
> ```

请问您实现了近似30FPS的效果了吗？作者在[这里](https://github.com/aipixel/GPS-Gaussian/issues/52#issuecomment-2241925842)提到30FPS时间包括**视频抠图**和**高斯球参数推理**，但是没有包括3DGS的render时间，请问想要实现live的效果应该怎么处理render？
