### ISSUE TITLE
实验设置问题

### ISSUE THREAD

**Issue by yqxuxuxu** [aipixel/GPS-Gaussian#35]
作者您好，论文中的实验设置是以8个相机进行训练，另外8个相机进行推理。但您所提供的GPS-GS_stage2_final.pth是16个相机训练的结果，是吗？
![image](https://github.com/aipixel/GPS-Gaussian/assets/152312410/ef156337-7351-4e43-93aa-0293502d6ac5)

**Comment by ShunyuanZheng** [comment]
论文里的数值结果虚拟数据部分，我也是用这个渲染代码，把相机数量设成8，测试新视点的数值。真实数据是用8台作为输入，另外8台作为新视点用来测试。

**Comment by yqxuxuxu** [comment]
> 论文里的数值结果虚拟数据部分，我也是用这个渲染代码，把相机数量设成8，测试新视点的数值。真实数据是用8台作为输入，另外8台作为新视点用来测试。

非常感谢您的答复。我使用真实数据的0和2作为src view在test_real_data.py做了测试，生成新视点1的渲染图，但是效果并不好？

**Comment by ShunyuanZheng** [comment]
针对不同角度的setting要单独训练的，如果要用0和2作为输入的话，需要在8相机setting下训一个模型。

**Comment by ShunyuanZheng** [comment]
训练数据造的更随机一点可能角度会有泛化性，因为我面向固定相机，所以这么造出来的数据角度是没法泛化的。同样，场景半径如果变了也是需要重新造一批适合这个场景的数据的。

**Comment by yqxuxuxu** [comment]
> 训练数据造的更随机一点可能角度会有泛化性，因为我面向固定相机，所以这么造出来的数据角度是没法泛化的。同样，场景半径如果变了也是需要重新造一批适合这个场景的数据的。
好的，了解了，谢谢您的答复。

**Comment by yqxuxuxu** [comment]
> 训练数据造的更随机一点可能角度会有泛化性，因为我面向固定相机，所以这么造出来的数据角度是没法泛化的。同样，场景半径如果变了也是需要重新造一批适合这个场景的数据的。

好的，了解了，谢谢您的答复。
