### ISSUE TITLE
关于 GPS 中深度单位制问题

### ISSUE THREAD

**Issue by hebing-sjtu** [aipixel/GPS-Gaussian#51]
作者您好，关于代码中深度/flow 的单位制问题，我想向您请教一些细节。

我试图将您的代码部署到实验室的采集设备上，然而在运行代码时，会出现左右两台相机的投影无法在空间中对齐的问题。初步判断可能是单位制不统一导致的。您外参文件中的单位是米（m）么?

**Comment by ShunyuanZheng** [comment]
您好，外参单位是米，代码中的depth是逆深度。

**Comment by hebing-sjtu** [comment]
感谢您迅速的回复，我尝试调整了外参，然而输出结果依然不理想。

我认为是我们的系统（相机分布以及场景直径）差异较大，因此无法复用您提供的 ckpt 权重文件，至少深度估计模块出现了无法忽略的问题。

我注意到您在训练的时候使用了 Twindom and THuman2.0 数据集，您在构建数据集的时候是否将视角与您系统的真实视角做了对齐？
![2](https://github.com/user-attachments/assets/4c970e4a-aaf8-4750-a22c-1edab8cd19d2)

**Comment by hebing-sjtu** [comment]
顺便问一下，您系统场景的直径是？

**Comment by ShunyuanZheng** [comment]
> 感谢您迅速的回复，我尝试调整了外参，然而输出结果依然不理想。
> 
> 我认为是我们的系统（相机分布以及场景直径）差异较大，因此无法复用您提供的 ckpt 权重文件，至少深度估计模块出现了无法忽略的问题。
> 
> 我注意到您在训练的时候使用了 Twindom and THuman2.0 数据集，您在构建数据集的时候是否将视角与您系统的真实视角做了对齐？ ![2](https://private-user-images.githubusercontent.com/97823602/348214053-4c970e4a-aaf8-4750-a22c-1edab8cd19d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODE1OTUsIm5iZiI6MTcyMDc4MTI5NSwicGF0aCI6Ii85NzgyMzYwMi8zNDgyMTQwNTMtNGM5NzBlNGEtYWFmOC00NzUwLWEyMmMtMWVkYWI4Y2QxOWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEwNDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MjU0YWI1YjhjMjZkODExZDJlNDc2OWQwMTRmYzg4MGQxMjZlMTgwYjVkZWFjMTFiMWEwNWEwMWU4ZGU1MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0SEbW2feflalg6PP-CZyahrYgiBP7Ag2DwU_xGdXEgw)

对，肯定是要按照场景设定重新虚拟数据来训练的，除了深度之外，相机夹角也是一个影响因素，我上传的checkpoint是在半径2m，夹角22.5的相机设定下训练和测试的。

**Comment by hebing-sjtu** [comment]
好的，感谢您提供的实验细节。我也注意到您的消融实验之一(table.2)讨论了使用8视角训练权重直接应用于6视角进行测试，尽管您提供了详细的客观指标，我想更多地了解这种训练测试相机分布不匹配时，除了客观质量的衰减，是否有主观可见的，由于空间难以对齐产生的不自然伪影。

**Comment by ShunyuanZheng** [comment]
22.5度的模型在30度左右的相机设定下测试应该没有问题，再大的角度可能会视觉效果下降明显。当然，深度也要注意和训练时候保持一致。

**Comment by hebing-sjtu** [comment]
再次感谢您详细的分享。
