### ISSUE TITLE
THuman2.0 dataloader 

### ISSUE THREAD

**Issue by arnabdeypolimi** [aipixel/GPS-Gaussian#53]
Can you please share the ENeRF data loader for THuman2.0 dataset? I see that you compare the method with ENeRF on Thuman2 dataset. Thanks in advance.

**Comment by ShunyuanZheng** [comment]
I send them to your email address (arnabdey0503@gmail.com), please kindly check.

**Comment by arnabdeypolimi** [comment]
thanks a lot
