### ISSUE TITLE
Inference with GT depth

### ISSUE THREAD

**Issue by tigfi2** [aipixel/GPS-Gaussian#59]
Thanks for your excellent work! I have a question regarding depth:
I am trying to run the model in inference mode using the ground truth depth maps provided by the render_data dataset using `required_pts=True` in function `get_test_item()`. I have noticed that the predicted and the ground truth have some sort of distortion between one and the other.
When generating a full pointcloud I obtain something like this:
 
![full_body_avatar_GTdepth](https://github.com/user-attachments/assets/24d660d3-6da9-4d25-a98c-39167ea6b721)

In comparison to the one generated with the prediction:
 
![full_body_avatar_depth](https://github.com/user-attachments/assets/013e6ca9-270a-436a-939f-81d6a31664cc)

Do you have any suggestion to get a better quality, or should I train the image features and depth encoder/decoder with the GT depths?

**Comment by ShunyuanZheng** [comment]
Thanks for your interest!

I think you should check whether the ```gt depth``` and the ```predicted depth``` have the same silhouette in 2D image. It looks like a mismatch in 2D image plane (the gray pixels are the background regions of source images). 
Also, it is a better choice to visualize the point cloud in MeshLab for a more in-depth analysis.

**Comment by tigfi2** [comment]
Thanks for your quick relply. Indeed, there is a mis match between the `gt depth` and the `predicted depth`, tou can sse the difference (`gt depth` - `predicted depth`) here:
![asdf](https://github.com/user-attachments/assets/7c2fddb4-77e8-47f5-abed-9a180319c199)
I also have the output in meshlab and the result is the same:
![full_body_avatar_GTdepth_meshlab](https://github.com/user-attachments/assets/fa27983a-efbc-4de6-95f4-552bbf9c95b3)
What can I do to solve this mismatch (they refer to the same image)?

**Comment by ShunyuanZheng** [comment]
The two image patterns may caused by stereo rectification, the silhouette of ```gt depth``` is identical to the RGB image which is not rectified. However, the ```gt flow``` must be rectified since it is used as supervision.

**Comment by ShunyuanZheng** [comment]
The ```new depth``` [here](https://github.com/aipixel/GPS-Gaussian/blob/76bcf3a54bda851b92792fbec9f4349673915fa1/lib/human_loader.py#L64-L85) is the rectified depth you need.

**Comment by tigfi2** [comment]
Thankyou for your help and quick response, it seems to work. 
Just a side note. When the resultant gaussian splatting is visualized in [animatter](https://antimatter15.com/splat/) there it looks as expected (although there are some occlusions depending on the angle):
![full_body_avatar_depth_good](https://github.com/user-attachments/assets/8ed60361-9f8e-4adc-a12d-1198345b5325)

In Meshlab, on the other hand, there are planes (I assume the occlusions come from here):
![full_body_avatar_depth_good_meshlab](https://github.com/user-attachments/assets/efd84757-099e-466c-a91c-010280976370)

What it the explanation?
