### ISSUE TITLE
Small Suggestions

### ISSUE THREAD

**Issue by kkaytekin** [aipixel/GPS-Gaussian#60]
Hi,
for better reusability of your work, here are two small suggestions:
1. Deterministic preprocessing:
Sharing your preprocessed data lifted the need to solve this issue, but if you would add a random seed to [here](https://github.com/aipixel/GPS-Gaussian/blob/76bcf3a54bda851b92792fbec9f4349673915fa1/prepare_data/render_data.py#L212), running this script on any dataset will be enough to obtain the same preprocessed data.

2. Fewer magic numbers:
Hard coding resolutions as in [here](https://github.com/aipixel/GPS-Gaussian/blob/76bcf3a54bda851b92792fbec9f4349673915fa1/lib/human_loader.py#L249C8-L249C26) and [here](https://github.com/aipixel/GPS-Gaussian/blob/76bcf3a54bda851b92792fbec9f4349673915fa1/lib/human_loader.py#L409) would cause unexpected errors if someone would like to run your code in different resolutions. The resolutions could instead be inferred from loaded image.

These are small points, but also easy failure modes I could spot so far. If you want, I can prepare a pull request!

**Comment by ShunyuanZheng** [comment]
Thanks for your suggestions, I have fixed them.
