### ISSUE TITLE
Camera Extrinsics in the rendering code

### ISSUE THREAD

**Issue by Lewis-lv0** [aipixel/GPS-Gaussian#63]
Hi @ShunyuanZheng , thanks for the amazing work. I am wondering if the exported extrinsics in your rendering code ([link to the line](https://github.com/aipixel/GPS-Gaussian/blob/main/prepare_data/render_data.py#L187)) are world-to-camera or camera-to-world? I cannot find the reference docs for taichi three.. Thank you in advance!

**Comment by ShunyuanZheng** [comment]
Hi, thanks for your interest. The extrinsic matrixes of both the rendered data and the captured real-world data are world-to-camera.

**Comment by Lewis-lv0** [comment]
Thanks closing this issue
