### ISSUE TITLE
项目主页中放出的权重是在所有数据集上一起训练的吗？我直接使用这个权重对THuman2.0做了测试，指标远高于论文中报告的情况。是否有在单个数据集上训练的权重用于复现论文中的指标？

### ISSUE THREAD

**Issue by dodododddo** [aipixel/GPS-Gaussian#66]

**Comment by ShunyuanZheng** [comment]
您好，上传的权重是16相机设定下的，论文里的结果是8相机设定下的。还有就是指标明显高的原因应该是在全图上做测试了，背景区域会让指标看起来明显偏高，文中我是在bbox内计算指标的。但是在比较数值的时候只要所有对比的方法都用统一方式就可以了，许多论文也确实是在全图上计算的。

**Comment by dodododddo** [comment]
了解了，感谢！
